embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/models/break0.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"palette\"\n"
  "  material: \"/light_and_shadows/materials/model/model_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/models/break1.png\"\n"
  "  }\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 1.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 2.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 2.0\n"
  "  data: 2.0\n"
  "  data: 2.0\n"
  "}\n"
  ""
}
